# Generated by Django 5.0.2 on 2025-07-02 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amendement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_modification', models.CharField(max_length=50)),
                ('type_modification', models.CharField(blank=True, max_length=255, null=True)),
                ('texte_amendement', models.TextField()),
                ('numero_article', models.CharField(max_length=50)),
                ('alinea', models.TextField(blank=True, null=True)),
                ('article', models.CharField(max_length=50)),
                ('texte_original', models.TextField()),
                ('texte_modifie', models.TextField()),
                ('justification', models.TextField()),
                ('date_insertion', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
