# Generated by Django 5.0.2 on 2025-07-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amendements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendement',
            name='nom_loi',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
