# Generated by Django 5.2.2 on 2025-07-09 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amendements', '0003_amendementfichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendement',
            name='fichier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amendements.amendementfichier'),
        ),
    ]
