# Generated by Django 5.2.2 on 2025-07-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amendements', '0004_amendement_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendementfichier',
            name='extracted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
