# Generated by Django 5.2.2 on 2025-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amendements', '0005_amendementfichier_extracted_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendementfichier',
            name='nom_personnalise',
            field=models.CharField(blank=True, help_text='Nom personnalisé du fichier (optionnel)', max_length=255, null=True),
        ),
    ]
