# Generated by Django 5.0.2 on 2025-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amendements', '0006_amendementfichier_nom_personnalise'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendement',
            name='numero_groupe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
