# Generated by Django 5.0.2 on 2025-07-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amendements', '0007_amendement_numero_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendement',
            name='article',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='nom_loi',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='numero_article',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='numero_groupe',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='numero_modification',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='type_modification',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='amendementfichier',
            name='nom_personnalise',
            field=models.CharField(blank=True, help_text='Nom personnalisé du fichier (optionnel)', max_length=1000, null=True),
        ),
    ]
