# Generated by Django 5.0.2 on 2025-07-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amendements', '0008_alter_amendement_article_alter_amendement_nom_loi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendement',
            name='champs_detectes',
            field=models.JSONField(blank=True, help_text='Champs détectés automatiquement par HuggingFace', null=True),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='article',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='nom_loi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='numero_article',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='numero_groupe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='numero_modification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='type_modification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='amendementfichier',
            name='nom_personnalise',
            field=models.CharField(blank=True, help_text='Nom personnalisé du fichier (optionnel)', max_length=255, null=True),
        ),
    ]
