# Generated by Django 5.0.2 on 2025-07-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amendements', '0009_amendement_champs_detectes_alter_amendement_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendement',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='texte_modifie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='texte_original',
            field=models.TextField(blank=True, null=True),
        ),
    ]
