# Generated by Django 6.1.1 on 2026-10-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amendements", "0010_alter_amendement_justification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amendement",
            name="texte_entete",
            field=models.TextField(
                blank=True,
                help_text="Texte d'en-tête brut de l'amendement (sert à la détection IA)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="amendement",
            name="champs_detectes",
            field=models.JSONField(
                blank=True,
                help_text="Champs détectés automatiquement (IA + règles)",
                null=True,
            ),
        ),
    ]
